### ISSUE TITLE
Bug/ add support for transcendental function for ourput parse

### ISSUE THREAD

**Issue by pfroehle-ccl** [bruderj15/Hasmtlib#3]
the following example response from cvc5 isn't supportet by the parser yet, indicated by the response (Sat. Nothing). Propable cause are  transcendental functions like sqrt, cos, etc. not being implemented yet.

```smtlib2
sat

)define-fun var_25 () Real (+ (- 4) (sqrt 16.0)))
(Sat,Nothing)
```

**Comment by studJBccl** [comment]
Transcendentals are not yet supported for the solver responses. Will add support very soon.
