### ISSUE TITLE
Observable sharing

### ISSUE THREAD

**Issue by bruderj15** [bruderj15/Hasmtlib#43]
Add observable sharing similar to what [ekmett/ersatz](https://github.com/ekmett/ersatz) does.
Is it as simple though?

From [Ersatz.Problem](https://github.com/ekmett/ersatz/blob/135107e998f299d3199b977f77a038a589a4f6d1/src/Ersatz/Problem.hs#L136):
```haskell
generateLiteral :: MonadSAT s m => a -> (Literal -> m ()) -> m Literal
generateLiteral a f = do
  let sn = unsafePerformIO (makeStableName' a)
  use (stableMap.at sn) >>= \ ml -> case ml of
    Just l -> return l
    Nothing -> do
      l <- literalExists
      stableMap.at sn ?= l
      f l
      return l
```

On the first glance this only seems to share variables. We can easily do that likewise too.
However, where is sharing of entire formula sub-trees?

**Comment by fabeulous** [comment]
> On the first glance this only seems to share variables. We can easily do that likewise too.
However, where is sharing of entire formula sub-trees?

I believe this happens in [Ersatz.Bits](https://github.com/ekmett/ersatz/blob/135107e998f299d3199b977f77a038a589a4f6d1/src/Ersatz/Bit.hs#L168) . Specifically:

```Haskell
runBit :: MonadSAT s m => Bit -> m Literal
runBit (Not c) = negateLiteral `fmap` runBit c
runBit (Var l) = return l
runBit (Run action) = action >>= runBit
runBit b = generateLiteral b $ \out ->
  assertFormula =<< case b of
    And bs    -> formulaAnd out `fmap` mapM runBit (toList bs)
    Xor x y   -> liftM2 (formulaXor out) (runBit x) (runBit y)
    Mux x y p -> liftM3 (formulaMux out) (runBit x) (runBit y) (runBit p)
```

This generates a fresh literal `out` per sub-formula `b` and asserts that `out <-> b`. Going forward any occurrence of `b` (with the same `StableName`)  is replaced by `out`, hence sharing the full sub-tree.

I guess for SMT-Lib the equivalent would turn

```Haskell
let a = 2 * x
in assert $ a === a + a
```
into something like
```
(declare-const c1 Int)
(assert (= c1 (* 2 x)))   ; c1 represents a
(declare-const c2 Int)
(assert (= c2 (+ c1 c1))) ; c2 represents a + a
(declare-const c3 Bool)
(assert (= c3 (= c1 c2))) ; c3 represents a === a + a
(assert c3)
```

**Comment by fabeulous** [comment]
> I am not sure how replacing each node in the expression with a new var will influence solver performance.

I also don't know how this would impact solver performance.

However not sharing expressions that are shared in the Haskell expressions can lead to the SMT expression growing exponentially compared to the Haskell expression. In something like
```Haskell
let a1 = x + x
    a2 = a1 + a1
    a3 = a2 + a2
    ...
in assert $ an === an 
```
each new let binding would lead to doubling the size of the SMT expression. With sharing it only grows linearly.
While this comes at the cost of adding linearly many fresh variables, I think that would be worth it.

Maybe as another data point, [SBV](https://github.com/LeventErkok/sbv/tree/master) seems to also introduce a variable per subexpression in [newExpr](https://github.com/LeventErkok/sbv/blob/dc250e3ee1ab6a132948a96e15d6e4cefff4a35f/Data/SBV/Core/Symbolic.hs#L1587). It goes even further by sharing equivalent subexpressions independent of their StableName.

**Comment by fabeulous** [comment]
The issue is likely down to `transformM1` traversing the expression bottom up, reallocating the expression before you call `makeStableName`.  That is
```Haskell
uniplate1 f (Plus x y) = Plus <$> f x <*> f y
```
will allocate a new Expression with a different StableName each time.

A paramorphism is probably more fitting here. Something like:
```Haskell
paraM1 :: (Monad m, Uniplate1 f cs, AllC cs b) => (forall a. AllC cs a => f a -> f a -> m (f a)) -> f b -> m (f b)
paraM1 f x = uniplate1 (paraM1 f) x >>= f x
```
then using
```Haskell
-- This is run once on every assertion.
runSharing :: (KnownSMTSort t, MonadSMT SMT m) => Expr t -> m (Expr t)
runSharing = paraM1 (
    \origExpr expr ->
      if isLeaf expr
      then return expr
      else case sortSing' expr of
        SBoolSort     -> share origExpr expr
        SIntSort      -> share origExpr expr
        SRealSort     -> share origExpr expr
        SBvSort _     -> share origExpr expr
        SArraySort _ _ -> share origExpr expr
        SStringSort   -> share origExpr expr)

-- Transformation of a single node
share :: (Equatable (Expr t), KnownSMTSort t, MonadSMT SMT m) => Expr t -> Expr t -> m (Expr t)
share origExpr expr = do
  let sn = unsafePerformIO (makeStableName' origExpr)
   in use (stableMap.at sn) >>= \mexpr' -> case mexpr' of  
        Just (SomeSMTSort expr') -> case geq (sortSing' expr) (sortSing' expr') of
          Nothing -> makeNode sn expr
          Just Refl -> return expr'
        Nothing -> makeNode sn expr
```
might work?

I haven't testing any of this, since I currently can't compile the library (I'll create another issue for that).

**Comment by fabeulous** [comment]
On second thought, while this should produce the correct SMT encoding, it will still do multiple traversals of each shared subexpression. Some kind of "lazy" para that delays the monadic effect of the recursion would be better I think.

```Haskell
lazyParaM1 :: (Monad m, Uniplate1 f cs, AllC cs b) => (forall a. AllC cs a => f a -> m (f a) -> m (f a)) -> f b -> m (f b)
lazyParaM1 f x = f x (uniplate1 (lazyParaM1 f) x)

runSharing :: (KnownSMTSort t, MonadSMT SMT m) => Expr t -> m (Expr t)
runSharing = paraM1 (
    \origExpr expr ->
      if isLeaf origExpr
      then return origExpr
      else case sortSing' origExpr of
        SBoolSort     -> share origExpr expr
        SIntSort      -> share origExpr expr
        SRealSort     -> share origExpr expr
        SBvSort _     -> share origExpr expr
        SArraySort _ _ -> share origExpr expr
        SStringSort   -> share origExpr expr)

-- Transformation of a single node
share :: (Equatable (Expr t), KnownSMTSort t, MonadSMT SMT m) => Expr t -> m (Expr t) -> m (Expr t)
share origExpr expr = do
  let sn = unsafePerformIO (makeStableName' origExpr)
   in use (stableMap.at sn) >>= \mexpr' -> case mexpr' of  
        Just (SomeSMTSort expr') -> case geq (sortSing' origExpr) (sortSing' expr') of
          Nothing -> expr >>= makeNode sn
          Just Refl -> return expr'
        Nothing -> expr >>= makeNode sn expr
```
